[tool.poetry]
name = "monitor-app"
version = "0.1.0"
description = ""
authors = ["hardwork9047 <tomatosimple1104@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.1.0"
flask-sqlalchemy = "^3.1.1"
pandas = "^2.2.3"
dotenv = "^0.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
